Proyecto1/urls.py
from django.contrib import admin
from django.urls import path
from AppCoder.views import mostrar_mi_template
from AppCoder.views import mostrar_tareas, mostrar_personas,cargar_personas,BuscarPersonas
from SocialTravel.views import index,PostList, PostDetail, PostCreate, PostUpdate,PostDelete,SignUp,Login,Logout,ProfileUpdate
from django.conf import settings
from django.conf.urls.static import static 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('mi-template/<nombre>/<apellido>',mostrar_mi_template),
    path('mis-tareas/<criterio>',mostrar_tareas, name="tareas"),
    path('',index, name="index"),
    path('personas/',mostrar_personas, name="personas"),
    path('personas/create',cargar_personas, name="personas-create"),
    path('personas/list',BuscarPersonas.as_view() ,name="personas-list"),
    path('post/list',PostList.as_view(),name="post-list"),
    path('post/<pk>/detail',PostDetail.as_view(),name="post-detail"),
    path('post/create',PostCreate.as_view(),name="post-create"),
    path('post/<pk>/update',PostUpdate.as_view(),name="post-update"),
    path('signup',SignUp.as_view(),name="signup"),
    path('login/', Login.as_view(), name="login"),
    path('logout/', Logout.as_view(), name="logout"),
    path('profile/<pk>/update', ProfileUpdate.as_view(), name="profile-update"),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

AppCoder/models.py
from django.db import models

class Tarea(models.Model):
    nombre = models.TextField(max_length=100)
    estado = models.TextField(max_length=100,default="por_hacer")
    creado_el = models.DateTimeField(auto_now_add=True)
    modificado_el = models.DateTimeField(auto_now=True)

    def terminar(self):
        self.estado = "terminado"


    def __str__(self):
        return f"{self.id} - {self.nombre}"


class Persona(models.Model):
    nombre = models.TextField(max_length=100)
    apellido = models.TextField(max_length=100)
    fecha_nacimiento = models.DateField()

    def __str__(self):
        return f"{self.id} - {self.nombre} - {self.apellido}"

SocialTravel/models.py
from django.db import models
from django.contrib.auth.models import User

class Post(models.Model):
    carousel_caption_tittle = models.CharField(max_length=30)
    carousel_caption_description = models.CharField(max_length=80)
    heading = models.CharField(max_length=15)
    description =models.CharField(max_length=120)
    publisher = models.ForeignKey(to=User, on_delete=models.CASCADE, related_name="publisher")
    imagen = models.ImageField(upload_to="posts",null=True, blank="True")

    def __str__(self):
        return f"{self.id} - {self.heading}"

class Profile(models.Model):
    user = models.OneToOneField(to=User, on_delete=models.CASCADE, related_name="profile")
    instagram = models.CharField(max_length=100)
    imagen = models.ImageField(upload_to="profiles", null=True, blank=True)

AppCoder/forms.py
from django import forms

class PersonaForm(forms.Form):
    nombre = forms.CharField(max_length=100)
    apellido = forms.CharField(max_length=100)
    fecha_nacimiento = forms.DateField()

class BuscarPersonasForm(forms.Form):
    criterio_nombre = forms.CharField(max_length=100)

AppCoder/views.py
from django.shortcuts import render
from AppCoder.models import Tarea,Persona
from AppCoder.forms import PersonaForm, BuscarPersonasForm
from django.views.generic import ListView

def mostrar_mi_template(request, nombre, apellido):
    context = {
        "nombre" : nombre,
        "apellido" : apellido,
        "notas": [5,6,7,8,9,10]
    }
    return render(request, "AppCoder/index.html", context)

def mostrar_tareas(request,criterio):
        if criterio == "todo":
            tareas = Tarea.objects.all()
        elif criterio:
            tarea = Tarea.objects.filter(nombre=criterio).all()
        return render(request,"AppCoder/tareas.html",{"tareas":tareas})

def mostrar_personas(request):

        personas = Persona.objects.all()
        total_personas = len(personas)
        context = {
            "personas":personas,
            "total_personas":total_personas,
            "form": PersonaForm(),
        }
        return render(request,"AppCoder/personas.html",context)

def cargar_personas(request):

    f = PersonaForm(request.POST)
    context= {
        "form":f
    }

    if f.is_valid():
        Persona(nombre=f.data["nombre"], apellido=f.data["apellido"],
        fecha_nacimiento=f.data["Fecha_nacimiento"] ).save()
        context['form'] = PersonaForm()
    
    context["Personas"] = Personas.objects.all()
    context["Total_de_Personas"] =len(Total_de_Personas)
    return render(request,"AppCoder/personas.html",context)

class BuscarPersonas(ListView):
    model = Persona
    context_objec_name="personas"

    def get_query(self):
        f = BuscarPersonasForm(self.request.GET)
        if f.is_valid():
            return persona.objects.filter(nombre__icontains=f.data["criterio_nombre"]).all()
        return Personas.objects.none()
    



    

SocialTravel/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView,CreateView,UpdateView, DeleteView
from SocialTravel.models import Post,Profile
from django.urls import reverse_lazy
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin


def index(request):
    context = {
        "posts": Post.objects.all()
    }
    return render(request,"SocialTravel/index.html",context)

class PostList(ListView):
    model = Post
    #Post.objects.all() se utiliza la query para buscar lista   

class PostDetail(DetailView):
    model = Post
    #Post.objects.get(id=pk)

class PostCreate(LoginRequiredMixin, CreateView):
    model = Post
    success_url = reverse_lazy("post-list")
    fields = '__all__' #o si quiere usarse algunos campos , se usa lista con los nombres de los campos 
    # ['carousel_caption_tittle','carousel_caption_description']

class PostUpdate(LoginRequiredMixin,UserPassesTestMixin,UpdateView):
    model = Post
    success_url = reverse_lazy("post-list")
    fields = '__all__'

    def test_func(self):
        user_id = self.request.user.id
        post_id = self.kwargs.get('pk')
        return Post.objects.filter(publisher=user_id, id=post_id).exists()

    def handle_no_permission(self):
        return render(self.request,"SocialTravel/not_found.html")

class PostDelete(LoginRequiredMixin,UserPassesTestMixin,DeleteView):
    model = Post
    success_url = reverse_lazy("post-list")

    def test_func(self):
        user_id = self.request.user.id
        post_id = self.kwargs.get('pk')
        return Post.objects.filter(publisher=user_id, id=post_id).exists()

    def handle_no_permission(self):
        return render(self.request,"SocialTravel/not_found.html")

class SignUp(CreateView):
    form_class = UserCreationForm
    template_name = 'registration/signup.html'
    success_url = reverse_lazy('post-list')

class Login(LoginView):
    next_page = reverse_lazy("post-list")

class Logout(LogoutView):
    template_name = 'registration/logout.html'

class ProfileUpdate(UpdateView):
    model = Profile
    fields = '__all__'
    

AppCoder/templates/AppCoder/base1.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=, initial-scale=1.0">
    <title>{% block tittle %} {% endblock %}</title>
</head>
<body>

<h1>{% block titulo%} {% endblock %}</h1>

{% block listado%} {% endblock %}


</body>
</html>

AppCoder/templates/AppCoder/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    Hola esto es una plantilla desde Django!
        <p style="color:red">Mi nombre es: {{nombre}}</p>
        <p style="color:green">Mi apellido es: {{apellido}}</p>

        <h3> Notas del alumno: </h3>
        <p>
            {% for nota in notas %}
                {% if nota > 6 %}
                <p style="color:green">{{nota}}</p>
                {% else %}
                <p style="color:red">{{nota}}</p>
                {% endif %}
                <br>
            {% endfor %}
        </p>
</body>
</html>

AppCoder/templates/AppCoder/persona_list.html
{% extends "AppCoder/base1.html"%}

{% block titulo%} Listado de personas {% endblock %}

{% block listado %}

<form>
    <p>
    <label for="id_criterio_nombre">Criterio</label>
    <input type"text" name="criterio_nombre" maxlength="100" required"" id="criterio_nombre">
    </p>
    <p>
        <input type="submit" value="Buscar">
    </p>
</form>
<url>
    {% for persona in personas %}
     <li>{{persona}}</li>
     {% endfor %}
</url>

{% endblock %}

{% block title %} Total: {{total_personas}} {% endblock %}

AppCoder/templates/AppCoder/personas.html
{% extends "AppCoder/base1.html"%}

{% block titulo%} Listado de personas {% endblock %}

{% block listado %}

<form action="{% url 'personas-create' %}" method="POST">
    {% csrf_token %}
   {{form.as_p}}
   <input type="submit" value="Guardar">
</form>

<url>
    {% for persona in personas %}
     <li>{{persona}}</li>
     {% endfor %}
</url>

{% endblock %}

{% block title %} Total: {{total_personas}} {% endblock %}

AppCoder/templates/AppCoder/tarea.html
{% extends "AppCoder/base1.html"%}

{% block titulo%} Listado de Tareas {% endblock %}

{% block listado %}
    <url>
        {% for tarea in tareas %}
         <li>{{tarea}}</li>
         {% endfor %}
    </url>

{% endblock %}

SocialTravel/templates/SocialTravel/Post_list.html
{% extends "SocialTravel/base.html" %}

{% block main %}<url>
   <h1>Lista de Post </h1>
   {% for post in object_list%}
   <li>
      {{post}}
      <a href="{% url 'post-detail' post.id %}"> Detalle</a>
      {% if user.is_authenticated and post.publisher == user.id %}
      <a href="{% url 'post-update' post.id %}"> Actualizar</a>
      <a href="{% url 'post-delete' post.id %}"> Borrar</a>
      {% endif %}
   </li>
   {% endfor %}
   </url>
   {% endblock %}

SocialTravel/templates/SocialTravel/base.html
<!DOCTYPE html>
<!-- saved from url=(0022)http://localhost:8000/ -->
<html lang="en">
  
<head>
    {% load static %}
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">

    
    
    
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.84.0">
    <title>Carousel Template · Bootstrap v5.0</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.0/examples/carousel/">

    

    <!-- Bootstrap core CSS -->
<link href="{% static 'SocialTravel/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Favicons -->
<link rel="apple-touch-icon" href="https://getbootstrap.com/docs/5.0/assets/img/favicons/apple-touch-icon.png" sizes="180x180">
<link rel="icon" href="https://getbootstrap.com/docs/5.0/assets/img/favicons/favicon-32x32.png" sizes="32x32" type="image/png">
<link rel="icon" href="https://getbootstrap.com/docs/5.0/assets/img/favicons/favicon-16x16.png" sizes="16x16" type="image/png">
<link rel="manifest" href="https://getbootstrap.com/docs/5.0/assets/img/favicons/manifest.json">
<link rel="mask-icon" href="https://getbootstrap.com/docs/5.0/assets/img/favicons/safari-pinned-tab.svg" color="#7952b3">
<link rel="icon" href="https://getbootstrap.com/docs/5.0/assets/img/favicons/favicon.ico">
<meta name="theme-color" content="#7952b3">


    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>

    <!-- Custom styles for this template -->
    <link href="{% static 'SocialTravel/css/carousel.css' %}" rel="stylesheet">
  </head>
  <body>
    
<header>
  <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
    <div class="container-fluid">
      {% if user.profile.image %}  
      <a href="{% url 'profile-update' user.profile.id %}">
      <img src="{{user.profile.imagen.url}}" height="100%" width="36px" style="border-radius: 50%; margin-right:10px">
      </a>
    {% endif %}
      <a class="navbar-brand" href="{% url 'index' %}">Social Travel</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav me-auto mb-2 mb-md-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'post-create' %}">Nuevo Post</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'post-list' %}">Mis post</a>
          </li>
          {% if user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'logout' %}">{{user.username}} / Logout</a>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'login' %}">Login</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'signup' %}">Registrarme</a>
          </li>
          {% endif %}
        </ul>
        <form class="d-flex">
          <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success" type="submit">Search</button>
        </form>
      </div>
    </div>
  </nav>
</header>
{% block main %}
{% endblock%}

<script src="{% static 'SocialTravel/js/bootstrap.bundle.min.js' %}"></script>

      
  

</body></html>

SocialTravel/templates/SocialTravel/index.html
{% extends "SocialTravel/base.html" %}

{% block main %}

<main>

  <div id="myCarousel" class="carousel slide" data-bs-ride="carousel">
    <div class="carousel-inner">
      
        {% for post in posts%}
          {% if forloop.first%}
            <div class="carousel-item active">
          {% else %}
            <div class="carousel-item">
          {% endif %}
              <img src="{{post.imagen.url}}">
            <div class="container">
              <div class="carousel-caption text-start">
                <h1>{{post.carousel_caption_tittle}}</h1>
                <p>{{post.carousel_caption_description}}</p>
                <p><a class="btn btn-lg btn-primary" href="{% url 'post-detail' post.id %}">Ver mas</a></p>
                </a></p>
              </div>
            </div>
          </div>
        
        {% endfor %}
        
       
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#myCarousel" data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#myCarousel" data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
    </button>
  </div>


  <!-- Marketing messaging and featurettes
  ================================================== -->
  <!-- Wrap the rest of the page in another container to center all the content. -->

  <div class="container marketing">

    <!-- Three columns of text below the carousel -->
    <div class="row">

      {% for post in posts %}

      <div class="col-lg-4">
        <img src="{{ post.imagen.url }}" height="144" width="144">
        <h2>{{post.heading}}</h2>
        <p>{{post.description}}</p>
        <h4>{{post.publisher.username}}</h4>
        <p><a class="btn btn-secondary" href="{% url 'post-detail' post.id %}"> Ver Mas »</a></p>
      </div><!-- /.col-lg-4 -->
      {% endfor %}
   
    </div><!-- /.row -->


    <!-- START THE FEATURETTES -->

    
    <hr class="featurette-divider">

    <div class="row featurette">
      <div class="col-md-7 order-md-2">
        <h2 class="featurette-heading">El puente</h2>
        <p class="lead">vistas lindas del rio</p>
      </div>
      <div class="col-md-5 order-md-1">
        
          <img src="./curso_coder_house_files/puente-corrientes-resistencia.jpeg" height="400" width="400">
        

      </div>
    </div>

    
    <hr class="featurette-divider">

    <div class="row featurette">
      <div class="col-md-7 order-md-2">
        <h2 class="featurette-heading">Las cataratas</h2>
        <p class="lead">un destino imperdible</p>
      </div>
      <div class="col-md-5 order-md-1">
        
          <img src="./curso_coder_house_files/cataratas-del-iguazu-misiones.jpeg" height="400" width="400">
        

      </div>
    </div>

    


    <!-- /END THE FEATURETTES -->INDEX.

  </div><!-- /.container -->


  <!-- FOOTER -->
  <footer class="container">
    <p class="float-end"><a href="https://getbootstrap.com/docs/5.0/examples/carousel/#">Back to top</a></p>
    <p>© 2017–2021 Company, Inc. · <a href="https://getbootstrap.com/docs/5.0/examples/carousel/#">Privacy</a> · <a href="https://getbootstrap.com/docs/5.0/examples/carousel/#">Terms</a></p>
  </footer>
</main>

{% endblock %}

SocialTravel/templates/SocialTravel/not_found.html
{% extends "SocialTravel/base.html" %}

{% block main %}

<h1> REGISTRO NO EXISTE </h1>
{% endblock %}

SocialTravel/templates/SocialTravel/post_confirm_delete.html
{% extends "SocialTravel/base.html" %}

{% block main %}
<h1>Estas seguro de querer borrar el post {{post.heading}}??</h1>
<form method="POST">
    {% csrf_token %}
    {{form}}
    <input type="submit" value="Borrar">
</form>
{% endblock %}

SocialTravel/templates/SocialTravel/post_detail.html
{% extends "SocialTravel/base.html" %}

{% block main %}

<p>
    <h1>{{object.heading}}</h1>
    <br>
    <img src="{{ object.imagem.url }}" width="320px" height="100%">
    <br> 
    {{object.description}}
    <br>
    <a href="{% url 'index' %}">volver</a> 
<!-- se cambia al url index para que luego de entrar por carousel al volver vuelva al index -->

</p>
{% endblock %}

SocialTravel/templates/SocialTravel/post_form.html
{% extends "SocialTravel/base.html" %}

{% block main %}

<form method="POST" >
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="Guardar">
</form>
{% endblock %}

SocialTravel/templates/SocialTravel/profile_form.html
{% extends "SocialTravel/base.html" %}

{% block main %}
<h1>PROFILE </h1>
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="Guardar">
</form>
{% endblock %}